name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: x64
        
    - name: Setting up
      run: |
          sudo apt-get install -y git wget zip espeak libespeak-dev alsa-utils
        
    - name: Init environment
      run: |
        cd $GITHUB_WORKSPACE
        python -m pip install -r requiment.txt
    - name: Run
      run: |
        cd $GITHUB_WORKSPACE
        python export_report.py
    - name: Upload to WETRANSFER 
      run: |
        cd $GITHUB_WORKSPACE
        curl -sL https://git.io/file-transfer | sh
        filename=$(ls *.pdf)
        ./transfer wet $filename